id: P6F57709F
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13345
  instance_id: http://purl.bdrc.io/resource/IE3JT13345
  collection_id: http://purl.bdrc.io/resource/PR0ET001
  language_id: None
  title:
    bo:
    - རྒྱ་ཆེན་བཀའ་མཛོད་ཀྱི་དཀར་ཆག
  alt_title: {}
  author: None
  publisher: DharmaDownload
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    7f31fa50f7e24633bb3ecf2c31c28c7c:
      title: ༄༅།་།འཇམ་མགོན་ཀོང་སྤྲུལ་རྒྱ་ཆེན་བཀའ་མཛོད།༼ཀ༽
      volume_number: 1
      base_file: UT3JT13345_001_0001.txt
      reference: http://purl.bdrc.io/resource/VL1BD8B44398A1A46D
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-30T16:36:17.159836'
last_modified_at: '2021-12-30T16:36:17.159843'
statistics:
  total_words: 7699
  total_non_words: 602
quality:
  non_words_ratio: 0.08
